### ISSUE TITLE
its not  working

### ISSUE THREAD

**Issue by subysmile** [phpish/shopify_private_app-skeleton#1]

**Comment by sandeepshetty** [comment]
I'll need more details to help you out.
- What is the error you are seeing?
- What version of PHP are you using?
- Have you followed all the instructions here: https://github.com/phpish/shopify_private_app-skeleton/blob/master/README.md

**Comment by subysmile** [comment]
Current PHP version: 5.5.1

error 

Warning: require(C:\xampp\htdocs\test\vendor\autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\test\get_shop.php on line 4

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\test/vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\test\get_shop.php on line 4

i have done all these steps
Create a private app.
Update conf.php with the private app's credentials.
Check out the .php files and see how they work. (e.g., http://path-to-new_prj/get_shop.php)

**Comment by sandeepshetty** [comment]
It looks like you didn't do the first step here (installing composer and getting dependencies using it): https://github.com/phpish/shopify_private_app-skeleton/blob/master/README.md
(Just updated the README to make it more clear.)

**Comment by subysmile** [comment]
i tried this one

 but seems this eror

phpish\shopify\CurlException: [77] error setting certificate verify
locations: CAfile: path_to_cert\cacert.pem CApath: none in
C:\xampp\htdocs\shopify_app-skeleton-master\oauth.php on line 26Array (
[method] => POST [uri] =>
https://element-8-dummy-shop.myshopify.com/admin/oauth/access_token [query]
=> Array ( ) [headers] => Array ( ) [payload] => Array ( [client_id] =>
*********\* [client_secret] =>
*********\* [code] => **********
) ) Array ( )

**Comment by sandeepshetty** [comment]
This is not an issue with the code. It looks like it's an issue with your machine. The SSL CA cert files are either corrupt, not accessible or missing. What version of Windows do you use?

I suggest you google for a solution to the problem.

Also, don't post client API keys and secrets into issues. (I've masked them in your comment above).

**Comment by sandeepshetty** [comment]
Closing this. If this was a problem with the code, please reopen it.

If it was a problem with your windows machine and if you've solved it, please leave a comment about it to help others.
