### ISSUE TITLE
PUT error

### ISSUE THREAD

**Issue by cwiggan** [phpish/shopify_private_app-skeleton#2]
phpish\shopify\CurlException: [6] Couldn't resolve host 'https'.

any idea what this means?

**Comment by sandeepshetty** [comment]
Looks like the URL you are trying to connect to incomplete. Is there more to the error, like line number, etc.?

**Comment by cwiggan** [comment]
phpish\shopify\CurlException: [6] Couldn't resolve host 'https' in /save_order.php on line 42Array ( [method] => PUT [uri] => https:/admin/orders/.json [query] => Array ( ) [headers] => Array ( [X-Shopify-Access-Token] => [content-type] => application/json; charset=utf-8 ) [payload] => Array ( [order] => Array ( [id] => [note_attributes] => Array ( [name] => ttes [value] => hi ) ) ) ) Array ( )

**Comment by sandeepshetty** [comment]
There seems to be a problem with the uri: `https:/admin/orders/.json`
Errors:
- `https:/` instead of `https://`
- `admin` instead of a proper Shopify hostname
- `orders/.json` instead of `orders.json`

Can you show me the code where it is making the call?

**Comment by cwiggan** [comment]
```
    # Making an API request 
    $product = $shopify('PUT /admin/orders/'.$juice['orderid'].'.json', array(), array
    (
        'order' => array
        (
            "id" => $juice['orderid'],
            "note_attributes" => array
            (
                "name"=> 'ttes',
                "value" => 'hi'
            )
        )
    ));
```

**Comment by cwiggan** [comment]
GET works fine btw

**Comment by sandeepshetty** [comment]
- `$juice['orderid']` seems to be empty which is why you get the `orders/.json` in the URI
- hostname doesn't seem to be set. I need to see the code that created `$shopify`

**Comment by cwiggan** [comment]
I found the problem thanx for trying to help

**Comment by sandeepshetty** [comment]
Alright. Closing this. If you think it might help others, you can mention the problem here.

**Comment by pritesh-ebiztrait** [comment]
Hi,

i have same issue faced in my custome API..

try
        {  
            $blog_id = '5617652';

```
        # Making an API request can throw an exception
        $article = $shopify('POST /admin/blogs/'.$blog_id.'/articles.json', array(), array(
            'article' => array(
                    "title" => $_POST['name'],
                    "author" => $_POST['email'],
                    "body_html" => $_POST['caption'],
                    "published" => false,
                    "summary_html" => "<img src='".$final_URL."' />"
                )
        ));
        echo "Your post added successfully.";
    }
    catch (shopify\ApiException $e)
    {
        # HTTP status code was >= 400 or response contained the key 'errors'
        echo $e;
        print_r($e->getRequest());
        print_r($e->getResponse());
    }
```

This is my code and error 

phpish\shopify\CurlException: [6] Couldn't resolve host 'https' in /home/shopiapp/public_html/lookbook/engine.php on line 33Array ( [method] => POST [uri] => https:/admin/blogs/5617652/articles.json [query] => Array ( ) [headers] => Array ( [X-Shopify-Access-Token] => [content-type] => application/json; charset=utf-8 ) [payload] => Array ( [article] => Array ( [title] => name [author] => test@gmail.com [body_html] => caption [published] => [summary_html] => 

i stuff at this point and i have set all url in https:// but no any solution get.

Thanks in advance

**Comment by bobsawyer** [comment]
I'm also getting this on a GET call:
`phpish\shopify\CurlException: [6] Couldn't resolve host 'https' in /home/builtfor/public_html/apps/rush-order-app/get_rush_orders.php on line 15
Array ( [method] => GET [uri] => https:/admin/orders.json?fulfillment_status=unshipped`

Line 15 in my code is this:
`$orders = $shopify('GET /admin/orders.json?fulfillment_status=unshipped');`

@cwiggan - what was your solution?

Thanks.

**Comment by bobsawyer** [comment]
@cwiggan, please update with your solution. I've been futzing with this for over a week and haven't made any headway. Would really appreciate it.

**Comment by rockyraccoon** [comment]
I need some help here as well. Same errors.

phpish\shopify\CurlException: [6] Couldn't resolve host 'https' in...

Array
(
    [method] =&gt; GET
    [uri] =&gt; https:/admin/shop.json
    [query] =&gt; 
    [headers] =&gt; Array
        (
            [X-Shopify-Access-Token] =&gt; 
            [content-type] =&gt; application/json; charset=utf-8
        )

```
[payload] =&gt; 
```

)
Array
(
)

**Comment by bobsawyer** [comment]
Good luck with that. I've been asking for months.

**Comment by neerajindiainfotech** [comment]
Fatal error:  Uncaught phpish\http\CurlException: [6] Couldn't resolve host '' in /home2/ahealthy/public_html/ghaslate.com/shopify/sample_app/vendor/phpish/http/http.php on line 18
  thrown in /home2/ahealthy/public_html/ghaslate.com/shopify/sample_app/vendor/phpish/http/http.php on line 39

I am getting this error.

I have tried everything but couldn't resolved it.Please help

**Comment by gautam14** [comment]
hi, 
When i try to run create_product.php on my localhost it showing this error, can someone tell what I am doing wrong.

Notice: Undefined index: shop in /var/www/kb_app/create_product.php on line 9

Notice: Undefined index: oauth_token in /var/www/kb_app/create_product.php on line 9
phpish\shopify\CurlException: [6] Could not resolve host: https in /var/www/kb_app/create_product.php on line 14Array ( [method] => GET [uri] => https:/admin/products.json [query] => [headers] => Array ( [X-Shopify-Access-Token] => [content-type] => application/json; charset=utf-8 ) [payload] => ) Array ( )

Thanks in advance
