### ISSUE TITLE
How to set this up as an "embedded app"?

### ISSUE THREAD

**Issue by jordanlev** [phpish/shopify_private_app-skeleton#3]
Hi,
Thank you for providing these php skeleton apps (this and the public one) -- they are incredibly helpful! What I cannot figure out, though, is how do I "embed" a private app into my shop's dashboard? All of the documentation seems to indicate that private and public apps are the same in terms of available functionality, but I see no way to make a private app show up in the shop dashboard like the public apps can. Any advice on this?

**Comment by sandeepshetty** [comment]
I haven't looked at building embedded apps yet. I'll try to spend some time on it next week and see if I can come up with an embedded app skeleton.

**Comment by bobsawyer** [comment]
This is relevant to my interests. How's that embedded skeleton coming along?

**Comment by sandeepshetty** [comment]
Haven't got around to doing this yet (busy with a new product I'm building). Give me a few more days.

**Comment by jordanlev** [comment]
I haven't found _anything_ in the docs or on the forums that would indicate this is possible. So I think you can't make a private embedded app. Rather, private apps must be hosted and accessed completely outside of the shopify dashboard (most likely as an integration in some other app or site you build that is isolated/separate from the shopify site).

Of course I'd love to be proved wrong so if you do figure it out that would be great to hear about :)

Thanks.

**Comment by sandeepshetty** [comment]
If what @jordanlev says is true, a workaround might be to just create a regular app and keep it unpublished.

**Comment by sandeepshetty** [comment]
A quick search brings up this (tl;dr what I suggested in my previous comment is the way to go):

> True private applications do not use OAuth and do not get listed in the Shopify admin, however you can create an App in your partners area, never publish it to the App store and only allow it to be installed on whichever shops you please. These Apps will be listed in the admin and will have full access to the EASDK.
> -- https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/new-embed-your-app-inside-of-shopify-176311#comment-179005

**Comment by sandeepshetty** [comment]
See also: http://ecommerce.shopify.com/c/shopify-apis-and-technology/t/embedded-private-apps-255723
