### ISSUE TITLE
GET error

### ISSUE THREAD

**Issue by bobsawyer** [phpish/shopify_private_app-skeleton#5]
Similar to the PUT error that was closed before, I'm getting the same error on GET:
`phpish\shopify\CurlException: [6] Couldn't resolve host 'https' in /home/podster/public_html/apps/rush-order-app/get_rush_orders.php on line 15
Array ( [method] => GET [uri] => https:/admin/orders.json?fulfillment_status=unshipped [query] => [headers] => Array ( [X-Shopify-Access-Token] => [content-type] => application/json; charset=utf-8 ) [payload] => ) Array ( )`

Line 15 as referenced above is:

`$orders = $shopify('GET /admin/orders.json?fulfillment_status=unshipped');`

If you look at the [method] portion of the Array, the [uri] contents are:

`https:/admin/orders.json?fulfillment_status=unshipped`

I've been beating my head against my keyboard over this for weeks. Any help would be greatly appreciated.

**Comment by rockyraccoon** [comment]
I'm having the same problem. Any solutions to this?

phpish\shopify\CurlException: [6] Couldn't resolve host 'https' in...

Array
(
    [method] =&gt; GET
    [uri] =&gt; https:/admin/shop.json
    [query] =&gt; 
    [headers] =&gt; Array
        (
            [X-Shopify-Access-Token] =&gt; 
            [content-type] =&gt; application/json; charset=utf-8
        )

```
[payload] =&gt; 
```

)
Array
(
)

**Comment by bobsawyer** [comment]
This clearly is no longer supported by the author. Moving on.
